services:
#    billetterie.example:
#        class: BilletterieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Billetterie.BilletterieManager:
        class: BilletterieBundle\Services\BilletterieManager

    Billetterie.Vacances:
        class: BilletterieBundle\Services\Vacances

    Billetterie.validator.dateVisite:
        class: BilletterieBundle\Validator\DateVisiteValidator
        arguments:
           - "@doctrine.orm.entity_manager"
           - "@Billetterie.Vacances"
           - "%ticketslimit%"
        tags:
            - {name: validator.constraint_validator, alias: billetterie_dateVisite}




    Billetterie.MailService:
        class: BilletterieBundle\Services\MailService
        arguments:
           - "@mailer"
           - "@twig"
           - "@billetterie.billetteriemanager"

    Billetterie.StripeService:
        class: BilletterieBundle\Services\StripeService
        arguments: ['%stripekey%']