services:
#    billetterie.example:
#        class: BilletterieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Billetterie.BilletterieManager:
        class: BilletterieBundle\Services\BilletterieManager
