<?php

namespace BilletterieBundle\Repository;

/**
 * billetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class billetRepository extends \Doctrine\ORM\EntityRepository
{
}
